= Installation

== Check compatibility

Kernel compatibility
Docker cannot run correctly if your kernel is older than version 3.10 or if it is missing some modules. To check kernel compatibility, you can download and run the check-config.sh script.

[source,bash]
----
curl https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh > check-config.sh
bash ./check-config.sh
----

== Install Docker Engine

link:https://docs.docker.com/engine/install/rhel/[Source]

=== *Install using the repository*

Before you install Docker Engine for the first time on a new host machine, you need to set up the Docker repository. Afterward, you can install and update Docker from the repository.

=== Set up the repository

Install the yum-utils package (which provides the yum-config-manager utility) and set up the repository.

[source,bash]
----
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
----

=== Install Docker Engine

Install the latest version of Docker Engine, containerd, and Docker Compose or go to the next step to install a specific version:

[source,bash]
----
sudo yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin
----

If prompted to accept the GPG key, verify that the fingerprint matches 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35, and if so, accept it.

This command installs Docker, but it doesn’t start Docker. It also creates a docker group, however, it doesn’t add any users to the group by default.

- Start Docker.

[source,bash]
----
sudo systemctl start docker
----

- Verify that Docker Engine is installed correctly by running the hello-world image.
[source,bash]
----
sudo docker run hello-world
----

This command downloads a test image and runs it in a container. When the container runs, it prints a message and exits.

This installs and runs Docker Engine. Use sudo to run Docker commands. Continue to link:https://docs.docker.com/engine/install/linux-postinstall/[Linux post-install] to allow non-privileged users to run Docker commands and for other optional configuration steps.
Upgrade Docker Engine

To upgrade Docker Engine, follow the link:https://docs.docker.com/engine/install/rhel/#install-using-the-repository[installation instructions], choosing the new version you want to install.

=== Configure Docker to start on boot

Most current Linux distributions (RHEL, CentOS, Fedora, Debian, Ubuntu 16.04 and higher) use systemd to manage which services start when the system boots. On Debian and Ubuntu, the Docker service is configured to start on boot by default. To automatically start Docker and Containerd on boot for other distros, use the commands below:

[source,bash]
----
sudo systemctl enable docker.service
sudo systemctl enable containerd.service
----
To disable this behavior, use disable instead.
[source,bash]
----
sudo systemctl disable docker.service
sudo systemctl disable containerd.service
----

=== Install Jenkins Container
[source,bash]
----
docker pull jenkins/jenkins
----

- link:https://github.com/jenkinsci/docker/blob/master/README.md[User manual]